version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /bio-diversity-genomics-garg.wdl
    testParameterFiles:
      - /bio-diversity-genomics-garg.inputs.json
    authors:
      - name: Shilpa Garg
        email: shilpa.garg@bio.ku.dk
